name: Create Pull Request for Release Branch
on:
  push:
    branches:
    - release/*
  workflow_dispatch:
    
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: |
          pr_list=$(gh pr list --base "HEAD_REF" --json number --jq '.[] | .number')
          if [ -n "$pr_list" ]; then
            echo "Pull request for branch HEAD_REF already exists."
          else
            gh pr create --fill --draft --base live
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
